/**
 * UniversalBridge TypeScript Definitions
 * Auto-generated by generate-registry.js
 * 
 * Usage:
 *   const bridge: UniversalBridge = require('./bridge');
 *   bridge.add(5, 3);  // Full autocomplete!
 */

export interface UniversalBridge {
    // Core functions
    reload(): UniversalBridge;
    _version: string;
    _getInfo(): { version: string; dllPath: string; functions: string[] };
    
    // Magic Store
    Store: {
        get(key: string): string;
        set(key: string, value: string): void;
        getInt(key: string): number;
        setInt(key: string, value: number): void;
        dump(): Record<string, any>;
    };
    
    // Enterprise: Callback Registration
    registerCallback(name: string, fn: (...args: any[]) => void): void;
    
    // Enterprise: Class Factory (Auto-Cleanup!)
    createClass(className: string): {
        create(): { handle: number; className: string };
        delete(wrapper: { handle: number }): void;
    } | null;
    
    // =========================================================================
    // Generated C++ Functions
    // =========================================================================
    hub_init(): void;
    hub_shutdown(): void;
    hub_version(): string;
    test_string(arg0: string): string;
    test_add(arg0: number, arg1: number): number;
    test_unicode(arg0: string): string;
    test_store_set(arg0: string): void;
    test_store_get(): string;
    hub_file_read(arg0: string): string;
    hub_file_write(arg0: string, arg1: string): number;
    hub_file_exists(arg0: string): number;
    hub_file_delete(arg0: string): number;
    hub_file_copy(arg0: string, arg1: string): number;
    hub_dir_create(arg0: string): number;
    hub_file_backup(arg0: string): number;
    hub_file_get_error(): string;
    hub_mmap_create(arg0: string, arg1: bigint): number;
    hub_mmap_open(arg0: string): number;
    hub_mmap_read(arg0: number, arg1: bigint, arg2: bigint): string;
    hub_mmap_write(arg0: number, arg1: bigint, arg2: string): number;
    hub_mmap_flush(arg0: number): number;
    hub_mmap_close(arg0: number): void;
    hub_mmap_size(arg0: number): bigint;
    hub_http_get(arg0: string): number;
    hub_http_post(arg0: string, arg1: string, arg2: string): number;
    hub_http_response_status(arg0: number): number;
    hub_http_response_body(arg0: number): string;
    hub_ws_create(): number;
    hub_ws_connect(arg0: number, arg1: string): number;
    hub_ws_send(arg0: number, arg1: string): number;
    hub_ws_close(arg0: number): void;
    hub_ws_is_connected(arg0: number): number;
    hub_ws_poll(arg0: number): string;
    hub_ftp_create(): number;
    hub_ftp_connect(arg0: number, arg1: string, arg2: string, arg3: string): number;
    hub_ftp_disconnect(arg0: number): void;
    hub_ftp_upload(arg0: number, arg1: string, arg2: string): number;
    hub_ftp_download(arg0: number, arg1: string, arg2: string): number;
    hub_ftp_delete(arg0: number, arg1: string): number;
    hub_ftp_mkdir(arg0: number, arg1: string): number;
    hub_crypto_sha256(arg0: string): string;
    hub_crypto_aes_encrypt(arg0: string, arg1: string): string;
    hub_crypto_aes_decrypt(arg0: string, arg1: string): string;
    hub_crypto_pbkdf2(arg0: string, arg1: string, arg2: number): string;
    hub_clipboard_clear(): void;
    hub_shell_execute(arg0: string): number;
    hub_shell_open_url(arg0: string): number;
    hub_shell_open_file(arg0: string): number;
    hub_shell_show_in_explorer(arg0: string): number;
    hub_env_get(arg0: string): string;
    hub_env_set(arg0: string, arg1: string): number;
    hub_env_expand(arg0: string): string;
    hub_base64_encode(arg0: string): string;
    hub_base64_decode(arg0: string): string;
    hub_cache_set(arg0: string, arg1: string): void;
    hub_cache_get(arg0: string): string;
    hub_cache_remove(arg0: string): void;
    hub_cache_clear(): void;
    hub_cache_size(): number;
    hub_compress_rle(arg0: string): string;
    hub_decompress_rle(arg0: string): string;
    hub_json_parse(arg0: string): number;
    hub_json_get_string(arg0: number, arg1: string): string;
    hub_json_get_number(arg0: number, arg1: string): number;
    bridge_version(): string;
    bridge_features(): string;
    bridge_get_last_error(): string;
    bridge_has_error(): number;
    bridge_poll_callbacks(): string;
    demo_add(arg0: number, arg1: number): number;
    demo_multiply(arg0: number, arg1: number): number;
    demo_greet(arg0: string): string;
    DemoCalc_new(): number;
    DemoCalc_delete(arg0: number): void;
    DemoCalc_getValue(arg0: number): number;
    DemoCalc_addTo(arg0: number, arg1: number): number;
    DemoCalc_reset(arg0: number): void;
    demo_divide(arg0: number, arg1: number): number;
    demo_sqrt(arg0: number): number;
    demo_start_task(arg0: number): void;
    DemoMath_sin(arg0: number): number;
    DemoMath_cos(arg0: number): number;
    DemoStr_length(arg0: string): number;
    DemoStr_upper(arg0: string): string;
    DemoCircle_new(arg0: number): number;
    DemoCircle_area(arg0: number): number;
    get_demo_counter(): number;
    set_demo_counter(arg0: number): void;
    get_demo_pi(): number;
    set_demo_pi(arg0: number): void;
    get_demo_user(): string;
    set_demo_user(arg0: string): void;
    DemoColor_Red(): number;
    DemoColor_Green(): number;
    DemoColor_Blue(): number;
    DemoStatus_Idle(): number;
    DemoStatus_Running(): number;
    DemoStatus_Done(): number;
    DemoStatus_Failed(): number;
    DemoPoint_create(): string;
    DemoVec3_create(): string;
    add(arg0: number, arg1: number): number;
    get_counter(): number;
    set_counter(arg0: number): void;
    get_name(): number;
    set_name(arg0: number): void;
    name_v0(): number;
    name_v1(): number;
    name_v2(): number;
    name_v3(): number;
    name_v4(): number;
    name_create(): string;
}

declare const bridge: UniversalBridge;
export default bridge;
