// Auto-generated by CPPBridge v3.1
// Do not edit manually - run 'npm run build:bridge' to regenerate

declare const bridge: {
  add(a: number, b: number): number;
  subtract(a: number, b: number): number;
  multiply(x: number, y: number): number;
  divide(a: number, b: number): number;
  greet(name: string): string;
  getVersion(): string;
  getAppInfo(): string;
  processText(input: string): string;
  stringLength(str: string): number;
  bridgeTest(): string;

  // Utility functions
  reload(): typeof bridge;
  _getInfo(): { version: string; environment: string; loadedFunctions: string[] };
  _version: string;
  _environment: string;
};

export = bridge;
