// Auto-generated by CPPBridge v3.2

declare const bridge: {
  test_int(a: number, b: number): number;
  test_double(a: number, b: number): number;
  test_bool(flag: number): number;
  test_string(input: string): string;
  test_void(value: number): void;
  test_json_object(json: string): string;
  test_json_array(json: string): string;
  test_return_json(): string;
  test_large_int(value: number): number;
  test_large_double(value: number): number;
  test_negative(value: number): number;
  test_zero(value: number): number;
  test_empty_string(input: string): string;
  test_divide(a: number, b: number): number;
  test_null_safety(input: string): string;
  test_error_code(type: number): number;
  test_store_set_string(key: string, value: string): void;
  test_store_get_string(key: string): string;
  test_store_set_int(key: string, value: number): void;
  test_store_get_int(key: string): number;
  test_async(iterations: number): Promise<string>;
  test_console_log(message: string): void;
  test_console_warn(message: string): void;
  test_console_error(message: string): void;
  test_long_string_length(input: string): number;
  test_special_chars(input: string): string;
  test_unicode(input: string): string;

  reload(): typeof bridge;
  _version: string;
};

export = bridge;
